name: Github ci-cd

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  BACKEND_CLASSPATH: 'zerone-backend/src/main/resources/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Creating a project copy
      uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package -DskipTests

  migration:
    runs-on: ubuntu-latest

    steps:
      - name: Creating a project copy
        uses: actions/checkout@v3
      - name: Updating database
        uses: liquibase-github-actions/update@v4.21.1
        with:
          changelogFile: ${{ secrets.DATABASE_CHANGELOG_PATH }}
          classpath: ${{ env.BACKEND_CLASSPATH }}
          url: ${{ secrets.DATABASE_URL }}
          username: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          logLevel: INFO

  test:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build, migration]
    steps:
      - name: Creating a project copy
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'maven'
      - name: Build with Maven
        run: mvn test
